[run]
init_cmds = [
  ["go", "build", "-o", "./build/github-release-tool"],
	["./build/github-release-tool"]
]
watch_all = true
watch_exts = [".go", ".ini", ".toml"]
watch_dirs = [
	"$WORKDIR/src",
]
build_delay = 5
cmds = [
    ["go", "build", "-o", "./build/github-release-tool"],
	["./bin/github-release-tool", "d", "go-gitea/gitea", "-s", "arm-7", "-o", "build"]
]
