[run]
init_cmds = [
  ["go", "build", "-o", "./bin/github-release-tool"],
	["./bin/github-release-tool"]
]
watch_all = true
watch_exts = [".go", ".ini", ".toml"]
watch_dirs = [
	"$WORKDIR/cmd",
	"$WORKDIR/models",
]
build_delay = 5
cmds = [
    ["go", "build", "-o", "./bin/github-release-tool"],
	["./bin/github-release-tool", "d", "go-gitea/gitea", "-s", "arm-7"]
]
