language: java
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
jdk:
  - oraclejdk8

before_script:
 - chmod +x ./gradle/buildViaTravis.sh

script: "./gradle/buildViaTravis.sh"
